[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes failures
    "I",    # import sorting
    "UP",   # upgrade syntax
    "TCH",  # type-checking imports
    "ANN",  # missing type hints
    "D",    # docstring style
    "B",    # bugbear warnings
    "C4",   # comprehension tweaks
    "PTH",  # prefer pathlib
    "T20",  # print statements
    "ARG",  # unused arguments
    "S",    # security issues
    "SIM",  # simplifications
    "PL",   # pylint rules
]
ignore = [
    "S101",     # allow plain asserts in tests
    "T201",     # allow print statements in CLI output
    "PLR2004",  # allow magic numbers in tests
    "D204",     # allow no blank line after class docstring
    "D203",     # incorrect-blank-line-before-class (incompatible with D211 no-blank-line-before-class)
    "D213",     # multi-line-summary-second-line (incompatible with D212 multi-line-summary-first-line)
]

